---
Name: ss-seo
---
SilverStripe\SiteConfig\SiteConfig:
  enable_seo_cache_lifetime: true
  extensions:
    - CatchDesign\SS\SEO\Extensions\SSRobotsConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - CatchDesign\SS\SEO\Extensions\CanonicalExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    properties:
      Quality: 70
  Psr\SimpleCache\CacheInterface.cacheblock:
    constructor:
      defaultLifetime: 2419200
