---
Name: ss-seo
After:
  - 'framework/*'
  - 'cms/*'
---
SiteConfig:
  enable_seo_cache_lifetime: true
  extensions:
    - Catch\SS_SEO\SSRobotsConfigExtension

Page:
  extensions:
    - Catch\SS_SEO\CanonicalExtension

GDBackend:
    default_quality: 70
