---
Name: ss-seo
---
SilverStripe\SiteConfig\SiteConfig:
  enable_seo_cache_lifetime: true
  extensions:
    - Catch\SS_SEO\SSRobotsConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Catch\SS_SEO\CanonicalExtension

GDBackend:
    default_quality: 70
