---
Name: ss-seo
After:
  - 'framework/*'
  - 'cms/*'
---
SiteConfig:
  enable_seo_cache_lifetime: true
  extensions:
    - Catch\SS-SEO\DataExtension\SSRobotsConfigExtension

Page:
  extensions:
    - Catch\SS-SEO\DataExtension\CanonicalExtension

GDBackend:
    default_quality: 70
