---
Name: ss-seo
---
# Extensions are no longer auto-applied. See README.md for setup instructions.

SilverStripe\SiteConfig\SiteConfig:
  enable_seo_cache_lifetime: true

SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    properties:
      Quality: 70
  Psr\SimpleCache\CacheInterface.cacheblock:
    constructor:
      defaultLifetime: 2419200
