---
Name: robot-project-routes
---
SilverStripe\Control\Director:
  rules:
    'robots.txt': 'CatchDesign\SS\SEO\Controllers\SSRobotsController'
# ---
# Name: extendedmodelascontrollerroutes
# Before: '*'
# After:
#   - framework/routes#rootroutes
#   - framework/routes#coreroutes
#   - cms/routes#modelascontrollerroutes
# ---
# Director:
#   rules:
#     '$URLSegment//$Action/$ID/$OtherID/$ID3/$ID4': 'ModelAsController'
